on:
  workflow_call:
    inputs:
      pattern:
        required: true
        type: string

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  targeted-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.9"
          terraform_wrapper: false
      - name: Setup Kustomize
        if: "!github.event.pull_request.head.repo.fork"
        uses: fluxcd/pkg/actions/kustomize@1bfad582060d2d6e464756fbd5d7a2b2fa4f75b9 # main
      - name: Run tests
        run: |
          make install-envtest
          make TARGET="${{ inputs.pattern }}"     target-test
