on:
  workflow_call:
    inputs:
      pattern:
        required: true
        type: string

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  targeted-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Terraform
        run: |
          export TF_VERSION=1.3.9
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip -q terraform_${TF_VERSION}_linux_amd64.zip
          mv terraform $(which terraform)
          terraform --version
      - name: Setup Kustomize
        if: "!github.event.pull_request.head.repo.fork"
        uses: fluxcd/pkg/actions/kustomize@7b3f43cb99b8203e18daa0d27063103709a29388 # main
      - name: Run tests
        run: |
          make install-envtest
          make TARGET="${{ inputs.pattern }}"     target-test
