on:
  workflow_call:
    inputs:
      pattern:
        required: true
        type: string

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  targeted-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Terraform
        run: |
          export TF_VERSION=1.3.9
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip -q terraform_${TF_VERSION}_linux_amd64.zip
          mv terraform $(which terraform)
          terraform --version
      - name: Setup Kustomize
        if: "!github.event.pull_request.head.repo.fork"
        uses: fluxcd/pkg/actions/kustomize@1bfad582060d2d6e464756fbd5d7a2b2fa4f75b9 # main
      - name: Run tests
        run: |
          make install-envtest
          make TARGET="${{ inputs.pattern }}"     target-test
