name: verify

on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
      - 'MAINTAINERS'
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Verify
        run: make verify
